### ISSUE TITLE
partner_invoice_id violates not-null constraint on invoice creation

### ISSUE THREAD

**Issue by dstags-LO** [bista-sales/bista_avalara_salestax#1]
Having an issue after loading this module. Appears as though partner_invoice_id is returning null when trying to create invoice. Would someone be able to point me in the right direction?

Here is the stack trace:

2016-08-22 19:48:32,120 2993 ERROR LOPROD openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 176, in create_invoices
    res = sale_obj.manual_invoice(cr, uid, sale_ids, context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 466, in manual_invoice
    self.signal_workflow(cr, uid, ids, 'manual_invoice')
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3571, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 187, in _execute
    id_new = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/odoo/addons/sale_stock/sale_stock.py", line 149, in action_invoice_create
    res = super(sale_order,self).action_invoice_create(cr, uid, ids, grouped=grouped, states=states, date_invoice = date_invoice, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 572, in action_invoice_create
    res = self._make_invoice(cr, uid, order, il, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/bista_avalara_salestax/sale_order.py", line 113, in _make_invoice
    inv_id = super(sale_order, self)._make_invoice(cr, uid, order, lines, context=None)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 443, in _make_invoice
    inv_id = inv_obj.create(cr, uid, inv, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/bista_avalara_salestax/account_invoice.py", line 279, in create
    return super(account_invoice, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4100, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4244, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "partner_invoice_id" violates not-null constraint
DETAIL:  Failing row contains (21, null, null, 0.00, SO0000011, null, null, null, 1, 3, 2016-08-22 19:18:55.83866, 1, null, null, null, 18, null, none, 1, null, draft, null, out_invoice, null, 996, f, null, null, null, null, 2016-08-22 19:18:55.83866, 1, 1, SO0000011, null, , f, null, null, f, f, null, 1, LOWH, f, null, null, null, null, , null, null, null, Stags Training Company

**Comment by bista-sales** [comment]
Hello dstags-LO ,

Issue is resolve in commit #96185cfd1c4290677e0a4ae8d1c20c77c21a9b50
Please take a pull for latest code.

Thanks.

**Comment by dstags-LO** [comment]
I appreciate you taking a look at this and making changes to the code base.

Unfortunately, it did not resolve my issue. New Stacktrace:

2016-08-24 20:01:59,654 3750 INFO LOPROD werkzeug: 192.168.37.71 - - [24/Aug/2016 20:01:59] "POST /web/dataset/call_kw/sale.advance.payment.inv/search_read HTTP/1.1" 200 -
2016-08-24 20:01:59,666 3750 DEBUG LOPROD openerp.http.rpc.request: call_button: sale.advance.payment.inv create_invoices, [[19],
 {'active_id': 14,
  'active_ids': [14],
  'active_model': 'sale.order',
  'lang': 'en_US',
  'open_invoices': True,
  'params': {'action': 308},
  'search_disable_custom_filters': True,
  'tz': 'US/Eastern',
  'uid': 1}]
2016-08-24 20:01:59,980 3750 ERROR LOPROD openerp.sql_db: bad query: INSERT INTO "account_invoice" ("id", "origin", "comment", "check_total", "reference", "payment_term", "company_id", "currency_id", "is_add_validate", "partner_id", "tax_add_default", "fiscal_position", "user_id", "reference_type", "journal_id", "location_code", "tax_add_shipping", "type", "internal_number", "account_id", "state", "reconciled", "section_id", "warehouse_id", "date_invoice", "partner_invoice_id", "exemption_code", "name", "partner_shipping_id", "exemption_code_id", "sent", "shipping_address", "tax_add_invoice", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_invoice_id_seq'), 'SO0000014', NULL, '0.00', 'SO0000014', 3, 1, 3, false, 18, false, 1, 1, 'none', 1, 'LOWH', false, 'out_invoice', NULL, 996, 'draft', false, NULL, 1, NULL, NULL, '', '', NULL, NULL, false, 'Stags Training Company
{Redacted}
United States', true, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "partner_invoice_id" violates not-null constraint
DETAIL:  Failing row contains (32, null, null, 0.00, SO0000014, 3, null, null, 1, 3, 2016-08-24 19:32:15.067008, 1, 1, null, null, 18, null, none, 1, null, draft, null, out_invoice, null, 996, f, null, null, null, null, 2016-08-24 19:32:15.067008, 1, 1, SO0000014, null, , f, null, null, f, f, null, 1, LOWH, f, null, null, null, null, , null, null, null, Stags Training Company
24 Flint Lock Circle
Rochester, New York ..., t).

2016-08-24 20:01:59,981 3750 ERROR LOPROD openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 176, in create_invoices
    res = sale_obj.manual_invoice(cr, uid, sale_ids, context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 466, in manual_invoice
    self.signal_workflow(cr, uid, ids, 'manual_invoice')
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3571, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 187, in _execute
    id_new = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/odoo/addons/sale_stock/sale_stock.py", line 149, in action_invoice_create
    res = super(sale_order,self).action_invoice_create(cr, uid, ids, grouped=grouped, states=states, date_invoice = date_invoice, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 572, in action_invoice_create
    res = self._make_invoice(cr, uid, order, il, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/bista_avalara_salestax/sale_order.py", line 113, in _make_invoice
    inv_id = super(sale_order, self)._make_invoice(cr, uid, order, lines, context=None)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/sale/sale.py", line 443, in _make_invoice
    inv_id = inv_obj.create(cr, uid, inv, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/bista_avalara_salestax/account_invoice.py", line 288, in create
    return super(account_invoice, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4100, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4244, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "partner_invoice_id" violates not-null constraint
DETAIL:  Failing row contains (32, null, null, 0.00, SO0000014, 3, null, null, 1, 3, 2016-08-24 19:32:15.067008, 1, 1, null, null, 18, null, none, 1, null, draft, null, out_invoice, null, 996, f, null, null, null, null, 2016-08-24 19:32:15.067008, 1, 1, SO0000014, null, , f, null, null, f, f, null, 1, LOWH, f, null, null, null, null, , null, null, null, Stags Training Company
24 Flint Lock Circle
Rochester, New York ..., t).
" while evaluating
u'action_invoice_create()'

**Comment by dstags-LO** [comment]
To add to this, here is the corresponding record from sale_order table:

14;"";"2016-08-24 19:31:38.878269";1;"";"2016-08-24 20:00:49";18;5.04;9;1;63.00;3;"2016-08-24 20:01:54";1;"";"manual";1;1;;"2016-08-24 19:32:07.647985";18;1;"2016-08-24";68.04;;"SO0000014";18;"manual";"direct";;1;f;;f;f;"LOWH";f;"";5.04;"Stags Training Company
24 Flint Lock Circle
Rochester, New York 14624
United States";;0.00;t

Using the same res_partner record for partner_invoice_id and partner_shipping_id.

res_partner record data:

18;"Stags Training Company";1;"";"";"2016-08-22 18:47:08.238448";0;"";"";"";"24 Flint Lock Circle";"Rochester";"Stags Training Company";"14624";;"";235;;f;"";"";t;"";t;"";"";f;0;"2016-08-24 19:18:33.941393";t;"US/Eastern";1;"en_US";1;"";"";"";"contact";f;;"";"";35;18;"always";"";f;"";"";"";"";f;;;"";;"";"";;;"";"1472068098-1-Cust-18";;;"";;;"";"";"";"";

If I create a record directly on the invoicing side without trying to create it from a sales order, I am able to create the invoice complete with appropriate tax data returned from the avatax service. If I however, try to create the invoice from the sales order, the stack traces above occur. Appears to be something with pulling the sales_order data into the invoice creation as the insert statement is missing the attribute data.

Thank you for your help!

DStags

**Comment by bista-sales** [comment]
Hello DStags,

I have tried to reproduce traceback, haven't face the error. Its working fine.
Can you check again. PFA video for your reference .
Also we have done some code improvement you can pull the branch to get latest code.

[avalara_video.zip](https://github.com/bista-sales/bista_avalara_salestax/files/436865/avalara_video.zip)

**Comment by dstags-LO** [comment]
Hi Bista-sales,

I watched the video and everything you showed works on my side as well. I run into the issue when clicking on the 'Create Invoice' button from the sales order. I am going to dump my database and try from scratch just to ensure there aren't entries causing the issue I am experiencing. 

I am also working on setting up in line debugging so I can step thru the code and see where it is failing. I will update when I have more information.

**Comment by bista-nimesh** [comment]
Hello DStags,

I have checked by creating invoice from the sales order as you have mention in your comment.
Its working fine.

**Comment by bista-sales** [comment]
Hello DStags,

PFA video for your reference. 

[avalara_sale_order.zip](https://github.com/bista-sales/bista_avalara_salestax/files/436972/avalara_sale_order.zip)

**Comment by dstags-LO** [comment]
Hey Bista,

After pulling the latest commit and diffing the code, I can see where the changes were made that fixed my issue. I appreciate the effort you put into this to get us up and running.

Thank you for your prompt assistance. I would recommend your company without a hesitation.

Best,

DStags
